name: Build project
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build project
        uses: eskatos/gradle-command-action@v1
        with:
          dependencies-cache-enabled: true
          arguments: clean build jacocoTestReport
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: build/reports/jacoco/report.xml
      - name: Deploy project
        uses: akhileshns/heroku-deploy@v3.4.6
        with:
          heroku_api_key: c1baf5cb-78b8-4b42-baee-32af41eda5ff
          heroku_app_name: "dh_homework3_by_alex_kartashov"
          heroku_email: "darth_moul@rambler.ru"
      - name: Checkout test repository
        uses: actions/checkout@v2
        with:
          repository: java-education/homework3-testing
          path: integration-tests
          ref: master
      - name: Run integration tests
        uses: eskatos/gradle-command-action@v1
        with:
          build-root-directory: integration-tests
          arguments: clean test -PtargetUrl=https://dh-homework3-by-alex-kartashov.herokuapp.com/
